name       : python-click
version    : 6.7
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/c/click/click-6.7.tar.gz : f15516df478d5a56180fbf80e68f206010e6d160fc39fa508b65e035fd75130b
license    : BSD-3-Clause
component  : programming.python
summary    : A simple wrapper around optparse for powerful command line utilities.
description: |
    A simple wrapper around optparse for powerful command line utilities.
builddeps  :
    - python-pytest
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        PYTHONPATH=$PWD py.test -v -k 'not test_legacy_callbacks'
    popd

    pushd $PKG_BUILD_DIR/py3build
        PYTHONPATH=$PWD py.test3 -v -k 'not test_legacy_callbacks'
    popd
