name       : python-click
version    : '7.0'
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/C/Click/Click-7.0.tar.gz : 5b94b49521f6456670fdb30cd82a4eca9412788a93fa6dd6df72c94d5a8ff2d7
license    : BSD-3-Clause
component  : programming.python
summary    : A simple wrapper around optparse for powerful command line utilities.
description: |
    A simple wrapper around optparse for powerful command line utilities.
builddeps  :
    - python-pytest
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test py.test -v
    %python3_test py.test3 -v
