name       : python-click
version    : 8.0.3
release    : 10
source     :
    - https://github.com/pallets/click/archive/refs/tags/8.0.3.tar.gz : 87dc1c1f2ba1501f825e78308cde654e1ddee253f5958292e77ef372a00318d3
homepage   : https://click.palletsprojects.com
license    : BSD-3-Clause
component  : programming.python
summary    : A simple wrapper around optparse for powerful command line utilities.
description: |
    A simple wrapper around optparse for powerful command line utilities.
builddeps  :
    - python-pytest
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v
