name       : python-click
version    : 7.1.2
release    : 7
source     :
    - https://github.com/pallets/click/archive/7.1.2.tar.gz : da626c7e5fa918a8c9bf9b5c0c0255b55469ca6b0c3cb2318ea0dc7eb05a56c3
homepage   : https://click.palletsprojects.com
license    : BSD-3-Clause
component  : programming.python
summary    : A simple wrapper around optparse for powerful command line utilities.
description: |
    A simple wrapper around optparse for powerful command line utilities.
builddeps  :
    - python-pytest
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v
