name       : python-click
version    : 8.1.3
release    : 11
source     :
    - https://github.com/pallets/click/archive/refs/tags/8.1.3.tar.gz : abb9959ec2d6cf198f70ca78ec2a5cd74110a6de728ecd19d8892ff65576f184
homepage   : https://click.palletsprojects.com
license    : BSD-3-Clause
component  : programming.python
summary    : A simple wrapper around optparse for powerful command line utilities
description: |
    Click is a Python package for creating beautiful command line interfaces in a composable way with as little code as necessary. It’s the “Command Line Interface Creation Kit”. It’s highly configurable but comes with sensible defaults out of the box. It aims to make the process of writing command line tools quick and fun while also preventing any frustration caused by the inability to implement an intended CLI API.
builddeps  :
    - python-pytest
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v
